# Generated by Django 2.2.4 on 2019-08-02 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(choices=[('Desk', 'Desk'), ('Laptop', 'Laptop'), ('IP Phone', 'IP Phone'), ('Project', 'Project')], max_length=100)),
                ('asset_serial_No', models.CharField(max_length=100)),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('date_purchased', models.DateTimeField()),
                ('asset_issued', models.BooleanField(default=False)),
                ('asset_image', models.ImageField(default='default.jpeg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsIssuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_location', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('Mezzanine', 'Mezzanine'), ('Second Floor', 'Second Floor'), ('Meeting Room', 'Meeting Room')], max_length=100)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Assets')),
                ('asset_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
